findtreasure:ReadInputs Game main
	g++ ReadInputs.o Game.o main.o -o findtreasure
ReadInputs:
	g++ -std=c++11 -c ReadInputs.cpp -o ReadInputs.o 
Game:
	g++ -std=c++11 -c Game.cpp -o Game.o 
main:
	g++ -std=c++11 -c main.cpp -o main.o